php:
  risky: false
  version: 8.1
  preset: recommended
  tab-width: 4
  use-tabs: true
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "nova"
      - "nova-components"
      - "storage"
      - "spark"
      - "vendor"
    name: "*.php"
    not-name:
      - "*.blade.php"
      - "*.vis.php"
      - "_ide_helper.php"