php:
  risky: false
  version: 7.0
  preset: recommended
  tab-width: 4
  use-tabs: true
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "nova"
      - "nova-components"
      - "storage"
      - "spark"
      - "vendor"
    name: "*.php"
